# Generated by Django 5.1.3 on 2024-11-18 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('nb_rooms', models.IntegerField()),
                ('nb_baths', models.IntegerField()),
                ('surface_area', models.FloatField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_associes', to='annonces.annonce')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_associes', to='annonces.equipement')),
            ],
            options={
                'unique_together': {('annonce', 'equipement')},
            },
        ),
        migrations.AddField(
            model_name='annonce',
            name='equipements',
            field=models.ManyToManyField(related_name='annonces', through='annonces.AnnonceEquipement', to='annonces.equipement'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='annonces.ville'),
        ),
    ]
