# Generated by Django 5.1.3 on 2024-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='nb_baths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='nb_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='surface_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
